services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:${TRAEFIK_HTTP_PORT}
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - ${TRAEFIK_HTTP_PORT}:${TRAEFIK_HTTP_PORT}   # ex: 8088:8088 (din .env)
      - 8080:8080                                   # dashboard Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro
    restart: unless-stopped

  ui:
    build:
      context: ./ui-landing
    labels:
      - "traefik.enable=true"
      # localhost:8088/ui
      - "traefik.http.routers.ui-local.rule=Host(`localhost`) && PathPrefix(`/ui`)"
      - "traefik.http.middlewares.ui-strip.stripprefix.prefixes=/ui"
      - "traefik.http.routers.ui-local.middlewares=ui-strip"
      - "traefik.http.services.ui.loadbalancer.server.port=80"
      # redirect din / -> /ui (pe localhost)
      - "traefik.http.routers.root-local.rule=Host(`localhost`) && Path(`/`)"
      - "traefik.http.routers.root-local.middlewares=to-ui"
      - "traefik.http.middlewares.to-ui.redirectregex.regex=^/$"
      - "traefik.http.middlewares.to-ui.redirectregex.replacement=/ui"
      - "traefik.http.middlewares.to-ui.redirectregex.permanent=false"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.6
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ${GRAFANA_DATA}:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      # localhost:8088/grafana
      - "traefik.http.routers.grafana-local.rule=Host(`localhost`) && PathPrefix(`/grafana`)"
      - "traefik.http.middlewares.grafana-strip.stripprefix.prefixes=/grafana"
      - "traefik.http.routers.grafana-local.middlewares=grafana-strip"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command:
      - start-dev
      - --http-port=8080
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
    volumes:
      - ${KEYCLOAK_DATA}:/opt/keycloak/data
    labels:
      - "traefik.enable=true"
      # localhost:8088/auth
      - "traefik.http.routers.auth-local.rule=Host(`localhost`) && PathPrefix(`/auth`)"
      - "traefik.http.middlewares.auth-strip.stripprefix.prefixes=/auth"
      - "traefik.http.routers.auth-local.middlewares=auth-strip"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped
